export const common = {
  overview: "Overview",
  borderManager: "Border Gates Management",
  activeGates: "Active Gates",
  transitRecords: "Transit Records",
  cargoValuation: "Cargo Valuation",
  complianceRate: "Customs Compliance",
  compoundRiskIndex: "Composite Risk",
  totalFines: "Fines Enforced",
  actions: "Oversight",
  status: "Status",
  registeredGates: "Registered Gates",
  transitLog: "Transit Logs",
  inspections: "Customs Inspections",
  riskAlerts: "Anomalies & Investigations",
  telemetryDevices: "Sensory Telemetry",
  identityAuditChain: "Audit Ledger Chain",
  registerTransit: "Register Trade / Pax",
  performInspection: "Create Inspection Note",
  resolveAlert: "Resolve Risk",
  regulatoryPolicies: "National Border Agreements",
  gateName: "Gate / Location",
  gateType: "Type",
  utilization: "Utilization",
  riskScore: "Risk",
  jurisdiction: "Jurisdiction",
  authority: "Authority",
  auditHash: "Hash Pointer",
  prevHash: "Prev Hash",
  timestamp: "Timestamp",

  borderOpsTitle: "Sovereign Border Operations & Revenue Control",
  borderOpsDesc: "Federal-Region Joint Border Command Center coordinating multi-point port entries, real-time customs duty evaluations, anti-evasion manifest audits, and high-security radar metrics.",
  pulseActivity: "Pulse Activity",
  nationalPulse: "National Monitoring Simulation System",
  civPaxCenter: "Civilian & Logistics Reception Center",
  intlInspector: "International Gateway Inspection Directorate",
  normalInspection: "Normal customs inspection performed without observations.",
  qualityInspectionCommittee: "Inspection & Quality Control Committee",
  antiSmugglingRoom: "Anti-Smuggling Operations Room",
  economicProtectionCommittee: "High Committee for National Economic Protection",
  securityProtocol: "SOVEREIGN GATEWAY SECURITY PROTOCOL Active:",
  levelJointCooperative: "LEVEL-4-JOINT-COOPERATIVE",
  onlyShowingRecords: "Only showing records associated with jurisdiction:",
  dbIsolationEnforced: "Cross-boundary database isolation is enforced.",
  searchPlaceholder: "Search by name or ID...",
  fedSovereigntyRule: "Federal Sovereignty Rule:",
  borderTetherText: "All joint board gates enforce real-time electronic cargo data mirroring to both Erbil and Baghdad mainframe directories under Joint Regulatory Treaty Section 14.",
  selectCheckpoint: "Select Checkpoint",
  transitType: "Transit Type",

  cargoMachinery: "Electrical Machinery & Generator",
  cargoRaw: "Raw & Mineral Materials",
  cargoFood: "Foodstuffs & Poultry Products",
  cargoClothing: "Clothing & Textile Products",
  cargoWeightPlaceholder: "Cargo weight verified in manifest...",
};
