export const DICTIONARY = {
  en: {
    title: 'IRAQ DIGITAL GATEWAY',
    subtitle: 'SOVEREIGN NATIONAL INFRASTRUCTURE',
    location: 'Official Trade & Customs Intelligence System',
    securityAccess: 'Access Clear: Zero-Trust Authorized Officer',
    langSelector: 'Language',
    dashboard: 'Command Center',
    analyzer: 'Customs AI Auditor',
    advisor: 'Sovereign AI Advisor',
    intelligence: 'Economic Corridor intelligence',
    checkpoints: 'Active Border Nodes & Checkpoints',
    services: 'Sovereign Technical Services',
    alerts: 'National Trade Integrity Alerts',
    manifestPreset: 'Load Sovereign Manifest Preset',
    orCustomText: 'OR Write / Modify Cargo Manifest Details',
    analyzeButton: 'Initiate Sovereign AI Compliance Audit',
    analyzing: 'Auditing via Custom Risk Brain (Gemini)...',
    resultTitle: 'Sovereign Intelligence Audit Report',
    complianceStatus: 'Compliance Status',
    suggestedHS: 'Verified HS-Code',
    riskFactor: 'Threat Intelligence Risk Index',
    calculatedTariff: 'Calculated National Duty Tariff',
    policyAdvisorTitle: 'Sovereign Policy Advisor Engine',
    policyWelcome: 'Sovereign Interoperability Chat. Ask about customs regulations, KRG-Baghdad tariff treaties, trade routes, borders, or anti-fraud protocols.',
    sendButton: 'Query Core Brain',
    economicCorridorTitle: 'Economic Corridor Forecast & Intelligence System',
    corridorVariables: 'Sovereign Planning Parameters',
    corridorDropdown: 'Target Economic Corridor',
    borderTradeFlow: 'Border Trade Volume Forecast',
    macroTrends: 'National Treasury Macro Trend Prediction',
    predictedRevenue: 'Predicted Dynamic Tariff Revenue Growth',
    predicting: 'Modeling Trade Architecture Trends...',
    generateForecast: 'Synthesize Intelligent Trade Forecast',
    backToDefault: 'Reset to Sovereign Baseline',
    checkpointDetails: 'Node Infrastructure Metrics',
    status: 'Operational Status',
    type: 'Logistics Class',
    dailyRevenue: 'Daily Dynamic Tariff Revenue (Est. IQD)',
    processedToday: 'Processed Cargo Batches',
    hourlyThroughput: 'Throughput',
    blockchainLogs: 'Zero-Trust Transaction Activity Hash Stream',
    integrityVerified: 'All gateway nodes reporting full compliance. Decoupled offline failover standby ACTIVE.',
    customStatus: 'FEDERAL SOVEREIGN INTEROPERABILITY: Baghdad ⇄ Erbil Integration fully synchronized.',
    currencyIQDUSD: 'IQD (Iraqi Dinars) & USD Equivalent',
  },
  ar: {
    title: 'بوابة العراق الرقمية',
    subtitle: 'البنية التحتية السيادية الوطنية للجمارك والتبادل التجاري',
    location: 'منظومة الاستخبارات الجمركية والتجارة الخارجية الاتحادية',
    securityAccess: 'تصريح الدخول: ضابط مفوض بالكامل - نظام صفر ثقة',
    langSelector: 'اللغة',
    dashboard: 'غرفة العمليات المركزية',
    analyzer: 'المدقق الذكي للمانيفست والامتثال',
    advisor: 'المستشار السيادي الفيدرالي',
    intelligence: 'تحليل الممرات والذكاء الاقتصادي',
    checkpoints: 'المنافذ والحدود والمنشآت جمركية النشطة',
    services: 'الخدمات السحابية والسيادية الإلكترونية',
    alerts: 'تنبيهات نزاهة التجارة والأمن الوطني الجمركي',
    manifestPreset: 'تحميل بيان شحنة سيادي معد مسبقاً',
    orCustomText: 'أو اكتب بتعديل حقول وتفاصيل بيان الشحنة',
    analyzeButton: 'بدء التدقيق الأمني الجمركي الفوري بالذكاء الاصطناعي',
    analyzing: 'جاري التحليل والتدقيق عبر العقل الاصطناعي السيادي الجمركي...',
    resultTitle: 'تقرير التدقيق الجمركي السيادي الذكي',
    complianceStatus: 'حالة الامتثال',
    suggestedHS: 'رمز النظام المنسق المعتمد (HS-Code)',
    riskFactor: 'مؤشر تقييم المخاطر واستخبارات التهديد',
    calculatedTariff: 'التعرفة الجمركية الاتحادية المحتسبة',
    policyAdvisorTitle: 'منظومة المستشار والاتفاقيات التجارية الموحدة',
    policyWelcome: 'مرحباً بك في بوابة الاستعلامات والمسائل التنظيمية. اسألني عن الاتفاقيات الجمركية بين بغداد وأربيل، نسب الرسوم الجمركية الموحدة، قانون الجمارك العراقي، وإجراءات البنك المركزي.',
    sendButton: 'أرسل الاستفسار للأمن جمركي',
    economicCorridorTitle: 'منظومة الاستشراف والتنبؤ الاقتصادي للممرات التجارية والمالية',
    corridorVariables: 'معاملات التخطيط والسياسات المالية السيادية',
    corridorDropdown: 'الممر الاقتصادي المستهدف للتحليل والنمذجة',
    borderTradeFlow: 'توقعات حجم التجارة وعبور المركبات',
    macroTrends: 'تقرير الاستشراف والاحتياطي التجاري والمالي للدولة',
    predictedRevenue: 'العائد الجمركي المتوقع خزينة الدولة (وفق النموذج التنبئي)',
    predicting: 'جاري توليد النماذج التنبئية بالذكاء الاصطناعي...',
    generateForecast: 'إنشاء تقرير الاستشراف وتنمية الإيرادات الممر المالي',
    backToDefault: 'إعادة التعيين للوضع السيادي الأساسي',
    checkpointDetails: 'تفاصيل ومؤشرات أداء المنفذ الجمركي',
    status: 'الحالة التشغيلية للمنفذ',
    type: 'صنف الشحن واللوجستيات',
    dailyRevenue: 'الإيرادات الجمركية اليومية المتوقعة (دينار عراقي)',
    processedToday: 'الشحنات والحاويات المنجزة اليوم',
    hourlyThroughput: 'معدل التدفق',
    blockchainLogs: 'سجل البلوكشين السيادي المقاوم للتلاعب (سلسلة الأنشطة)',
    integrityVerified: 'جميع العقد والروابط الحدودية تبلغ عن جاهزية كاملة. أنظمة الطوارئ المستقلة خارج الإنترنت مفعلة وفي وضع التأهب.',
    customStatus: 'التكامل السيادي الفيدرالي: مزامنة تامة لبيانات الاستيراد والتصدير بين بغداد والمنافذ الكوردستانية.',
    currencyIQDUSD: 'الدينار العراقي والمعادل بالدولار الأمريكي',
  },
  ku: {
    title: 'دەروازەی دیجیتاڵیی عێراق',
    subtitle: 'ژێرخانی نیشتمانیی سەروەری گومرگ و بازرگانی (IDG)',
    location: 'سیستەمی فەرمیی هەواڵگریی بازرگانی عێراقی فیدراڵ و هەرێمی کوردستان',
    securityAccess: 'ئاستی ڕێپێدان: ئەفسەری ڕێپێدراوی تەواو - متمانەی سفر',
    langSelector: 'زمان',
    dashboard: 'قۆناغی کۆنترۆڵ و بڕیاردان',
    analyzer: 'تدقیقی زیرەکی جومگەیی شتومەک',
    advisor: 'ڕاوێژکاری باڵای نیشتمانیی (زیرەکی دەستکرد)',
    intelligence: 'شیکردنەوەی ستراتیژی ڕێڕەوی ئابووری',
    checkpoints: 'خاڵە سنوورییەکان و دەروازە چالاکە گومرگییەکان',
    services: 'خزمەتگوزارییە ئەمنییە نیشتمانییە یەکگرتووەکان',
    alerts: 'ئاگادارکردنەوەکانی پاراستنی ئاسایشی بازرگانی و دەروازەکان',
    manifestPreset: 'بارکردنی نموونەی دۆکیومێنتی شحنات',
    orCustomText: 'یاخود زانیاری دۆکیومێنتی بارهەڵگر بنووسە یان دەستکاری بکە',
    analyzeButton: 'دەستپێکردنی ڕاپۆرتی پێوانەیی ئەمنی بە زیرەكي دەستکرد',
    analyzing: 'لێکۆڵینەوە و تدقیقکردن لە لایەن مێشکی گومرگی نیشتمانیی (Gemini)...',
    resultTitle: 'ڕاپۆرتی سەرەکی لێکۆڵینەوەی سەروەریی جومگەیی',
    complianceStatus: 'دۆخی یاسایی و پابەندبوون',
    suggestedHS: 'کۆدی پشتڕاستکراوی جیهانی (HS-Code)',
    riskFactor: 'پ پێوانەی مەترسی فێڵ یان هەڕەشە ئابوورییەکان',
    calculatedTariff: 'تاریفەی جومگەیی فیدراڵی عێراق',
    policyAdvisorTitle: 'ڕاوێژکاری تەواوی یاساکان و ڕێنمایی گومرگ و دەروازەکان',
    policyWelcome: 'بەخێربێن بۆ سیستەمی فەرمی گفتوگۆی یەکگرتووی نیشتمانیی. دەتوانیت پرسیار بکەیت سەبارعت بە ڕێککەوتنی جومگەیی بەغداد-هەولێر، یاسای باجی هاوبەش، و مامەڵە داراییەکان.',
    sendButton: 'ناردنی پرسیار بۆ مێشکی هەواڵگری',
    economicCorridorTitle: 'سیستەمی پێشبینی داهات و گەشەسەندنی ڕێڕەوی ئابووری',
    corridorVariables: 'پارامیتەرەکانی پلاندانانی دارایی و ئابووری دەوڵەت',
    corridorDropdown: 'ڕێڕەوی گشتی ئابووری دەستنیشانکراو',
    borderTradeFlow: 'ڕاپۆرتی پێشبینی بڕی تێپەڕبوونی ئۆتۆمبێل و بار',
    macroTrends: 'شیكردنەوەی پێشبینی کراو بۆ پاشەکەوت و گەشەی خەزێنەی گشتی فیدراڵ',
    predictedRevenue: 'داهاتی پێشبینیکراوی پڕبوونی بودجەی دەوڵەت لە تاریفەوە',
    predicting: 'گۆڕینەوەی سڕینەوەی پێوانەیی بازرگانی بۆ مۆدێلی زانستی...',
    generateForecast: 'دروستکردنی ڕاپۆرتی شیکاری و داهاتی ڕێڕەوی دیاریکراو',
    backToDefault: 'گەڕانەوە بۆ باری بنەڕەتی سەروەری نیشتمانیی',
    checkpointDetails: 'وردەکارییە لۆجستی و ئابوورییەکانی دەروازە سنوورییەکان',
    status: 'دۆخی چالاكی دەروازە',
    type: 'پۆلی لۆجستی',
    dailyRevenue: 'داهاتی خەمڵێندراوی ڕۆژانە (بە دیناری عێراقی)',
    processedToday: 'باری تەواوکراوی ئەمڕۆ',
    hourlyThroughput: 'خێرایی تێپەڕبوون',
    blockchainLogs: 'زنجیرەی بلۆکچەینی تایبەت بۆ کۆنتڕۆڵ و تۆماری بێ دەستكاری',
    integrityVerified: 'هەموو درەوازەکان و بنکەکان ڕێکوپێکی تەواو پیشان دەدەن. ئەگەری کارکردنی ئۆفلاین بەباشی ئامادە کراوە.',
    customStatus: 'هاوئاهەنگی نیشتمانیی فیدراڵ: داتای هاوردە و ناردنی نێوان عێراق و هەرێمی کوردستان یەکڕاست کراوه.',
    currencyIQDUSD: 'دیناری عێراقی و یەکسانبوون بە دۆلاری ئەمریکی',
  },
};

export function getDictionaryByLang(lang: 'en' | 'ar' | 'ku') {
  return DICTIONARY[lang] || DICTIONARY['en'];
}

export default DICTIONARY;
