export interface NarrativeDetail {
  title: string;
  shortExplanation: string;
  talkingPoints: string[];
  riskNote: string;
  acceptanceMessage: string;
}

export interface ScenarioNarrative {
  id: string; // matches scenario ids: federal_view, krg_view, joint_view, etc.
  en: NarrativeDetail;
  ar: NarrativeDetail;
  ku: NarrativeDetail;
}

export class PresentationNarrativeRegistry {
  private static narratives: Record<string, ScenarioNarrative> = {
    federal_view: {
      id: "federal_view",
      en: {
        title: "Federal Prime Minister Core Operations",
        shortExplanation: "Demonstrates Baghdad absolute sovereignty layer and data isolation boundary.",
        talkingPoints: [
          "Zero exposure of local KRG databases to Southern central intelligence nodes",
          "Secure execution of national-level strategic border policies and customs tariffs",
          "Verification of non-repudiation and cryptographic receipts generated by Baghdad central systems"
        ],
        riskNote: "Sovereign isolation policies strictly deny any direct database queries from regional units.",
        acceptanceMessage: "Federal executive checks validated: 100% compliant with Iraqi constitutional parameters."
      },
      ar: {
        title: "العمليات التنفيذية لدولة رئيس الوزراء الاتحادي",
        shortExplanation: "توضيح الصلاحيات الرقابية السيادية الكاملة لبغداد مع كفالة استقلالية الكيانات.",
        talkingPoints: [
          "عدم إطلاع الأجهزة الرقابية أو قواعد البيانات المركزية على الدفاتر الجمركية الداخلية للإقليم.",
          "تطبيق التعرفة الجمركية الاتحادية المقرة دستورياً على كافة المنافذ المشتركة.",
          "توثيق كافة الإيرادات جمركياً باستخدام مفاتيح أمنية اتحادية مشفرة."
        ],
        riskNote: "قواعد جدار الحماية تمنع منعاً باتاً استعلام أي جهة عن البيانات الخام خارج صلاحيتها.",
        acceptanceMessage: "تم تدقيق المكونات الرئاسية الاتحادية: مطابقة بنسبة 100% لمعايير السيادة الوطنية."
      },
      ku: {
        title: "کارە سەرەکییەکانی سەرۆک وەزیرانی فیدراڵ",
        shortExplanation: "پیشاندانی کایەی سەروەری گشتی دەسەڵاتی بەغدا لەگەڵ پاراستنی تەواوی سەربەخۆیی.",
        talkingPoints: [
          "هیچ دەرکەوتنێکی داتابەیسی هەرێم بۆ سەرچاوە فیدراڵییەکانی ناوەند بوونی نییە",
          "جێبەجێکردنی هاوتاکردنی باج و گومرگی فیدراڵی بە شێوازی یاسایی",
          "سەلماندنی یەکپارچەیی تۆبۆلۆژی و کلیلی پشتڕاستکردنەوە بۆ مامەڵە گشتییەکان"
        ],
        riskNote: "یاساکانی سیستەمەکە ڕێگری تەواو دەکەن لە هەر گەڕانێکی داتا لە دەرەوەی دەسەڵاتی ناوەندی.",
        acceptanceMessage: "کاریگەرییە فیدراڵییەکان سەرکەوتووبوون: ١٠٠٪ گونجاوە لەکەڵ مەرجە دەستوورییەکان."
      }
    },
    krg_view: {
      id: "krg_view",
      en: {
        title: "KRG Prime Minister Regional Dashboard",
        shortExplanation: "Demonstrates Kurdistan Region autonomous border management and cryptographic ledger protection.",
        talkingPoints: [
          "Complete local access speed with offline fallback for regional custom border posts",
          "Zero access from Federal officers to raw Kurdish citizen record databases",
          "Authentication signed purely with Kurdistan regional Hardware Security Modules (HSMs)"
        ],
        riskNote: "Regional databases completely block external administrative write and direct query requests.",
        acceptanceMessage: "Region autonomous compliance verified: 100% isolated regional state data."
      },
      ar: {
        title: "لوحة تحكم دولة رئيس وزراء إقليم كوردستان",
        shortExplanation: "تفعيل التحكم الذاتي وعمليات التدقيق الداخلي لحدود الإقليم لحماية خصوصية البيانات.",
        talkingPoints: [
          "معالجة البيانات الجمركية محلياً مع تفعيل مرونة العمل دون اتصال (Offline Fallback).",
          "تأكيد عدم إمكانية استعلام الموظفين الاتحاديين عن هويات أو ملفات الكوادر الإقليمية.",
          "تشهير التوقيع الإلكتروني الإقليمي عبر نظام أمني مخصص لبيان الأصالة الجمركية."
        ],
        riskNote: "قواعد عزل الأنظمة الجمركية تنشئ حاجزاً مبرمجاً يمنع دخول أي مستعلم خارجي.",
        acceptanceMessage: "تم تأكيد جاهزية إقليم كوردستان: حماية مطلقة بنسبة 100% لخصوصية بيانات الإقليم."
      },
      ku: {
        title: "داشبۆردی سەرۆک وەزیرانی هەرێمی کوردستان",
        shortExplanation: "پیشاندانی بەڕێوەبردنی کەرتی گومرگی سەربەخۆی هەرێمی کوردستان لە چوارچێوەیەکی پارێزراودا.",
        talkingPoints: [
          "کارکردنی دەروازە گومرگییەکان بە توانای لۆکاڵی تەواو لە کاتی نەمانی هێڵەکاندا",
          "پاراستنی ناوی هاوڵاتیانی هەرێم و زانیارییە کەسییەکان لە هەر چاودێرییەکی ناوەند",
          "واژۆکردنی بەڵگەنامە گومرگییەکان تەنیا لە ڕێگەی کلیلە پارێزراوەکانی هەرێم"
        ],
        riskNote: "داتابەیسەکانی هەرێم داواکارییەکانی بەغدا بۆ داتای خاوی هاوڵاتیان ڕەتدەکەنەوە.",
        acceptanceMessage: "یاساکانی سەربەخۆیی هەرێم ڕێگەپێدراون: داتای هەرێمی ١٠٠٪ پارێزراوە."
      }
    },
    joint_view: {
      id: "joint_view",
      en: {
        title: "Joint Integration & Cooperation Level",
        shortExplanation: "The Supreme Cooperative Dashboard showcasing trilingual real-time non-reversible matching stats.",
        talkingPoints: [
          "Zero raw identity, trade license, or tax ledger duplication across borders",
          "Cross-checks customs manifests using cryptographic hash values only",
          "Real-time visibility of matched border flow indicators without joint storage"
        ],
        riskNote: "Any cross-boundary leak in joint engines results in immediate system-wide policy shutdown.",
        acceptanceMessage: "Joint matching is secure: 0 raw leak incidents, 100% cooperative coverage achieved."
      },
      ar: {
        title: "المستوى المشترك للتعاون والتكامل الوطني",
        shortExplanation: "لوحة البيانات الفيدرالية الموحدة لعرض إحصاءات المطابقة الفورية دون تفاصيل البيانات.",
        talkingPoints: [
          "منع تام لتكرار رخص الاستيراد أو التنسيق الضريبي التفصيلي بين الطرفين.",
          "تطوير مطابقة البيانات الجمركية استناداً للتواقيع الإلكترونية المجردة.",
          "عرض مؤشرات العبور والنزاهة الإدارية دون تخزين أي وثيقة رسمية في خوادم مشتركة."
        ],
        riskNote: "حدوث أي خلل في قواعد عزل المطابقة يؤدي فوراً لقطع خيوط التبادل المشترك تلقائياً.",
        acceptanceMessage: "تم تدقيق المطابقة الرقمية: صفر تسريبات للبيانات، مطابقة آمنة بنسبة 100%."
      },
      ku: {
        title: "ئاستی هاوبەشی هەماهەنگی نیشتمانی",
        shortExplanation: "داشبۆردی یەکگرتووی نیشتیمانی بۆ پیشاندانی ڕێژەی هاوتاکردن بەبێ پێدانی زانیاری کەسی.",
        talkingPoints: [
          "ڕێگری تەواو لە کۆپی بوونی مۆڵەتەکانی هاوردەکردن لە دەروازە جیاوازەکاندا",
          "بەراوردکردنی ڕەوتی گومرگ تەنها لە ڕێگەی خوێندنەوەی کۆدی گشتی",
          "چاودێریکردنی جوڵەی گومرگی بە بێ خەزنکردنی داتای خاو لە خزمەتگوزاری هاوبەشدا"
        ],
        riskNote: "هەر هەوڵێک بۆ تێپەڕاندنی عزلەکە بە هاوبەش دەبێتە هۆی وەستاندنی بەیەکبەستنەکە.",
        acceptanceMessage: "هاوئاهەنگی نیشتمانی دڵنیایە: داتای هاوبەش بە تەواوی دوورە لە تێکەڵبوون."
      }
    },
    revenue_isolation: {
      id: "revenue_isolation",
      en: {
        title: "Sovereign Revenue Isolation Audit",
        shortExplanation: "Verify that raw ledger databases between Baghdad and Erbil remain completely isolated.",
        talkingPoints: [
          "Federal revenue ledgers cannot be modified or read by regional modules",
          "KRG revenue pipeline queries are completely filtered to block federal direct access",
          "Joint treasury audit only consumes non-reversible verification indicators"
        ],
        riskNote: "Sovereign isolation protocols enforce 100% database boundary isolation.",
        acceptanceMessage: "Revenue isolation audited: Zero financial leakage across boundaries."
      },
      ar: {
        title: "تدقيق وعزل الحسابات والإيرادات السيادية",
        shortExplanation: "التحقق البرمجي التام من انفصال خوادم الإيرادات العامة لبغداد وأربيل لحماية السيادة المالية.",
        talkingPoints: [
          "عدم تمكن وحدات الإقليم من قراءة أو كتابة أي قيد في دفاتر الإيرادات الاتحادية.",
          "تصفية تامة لاستعلامات حصص النفط والجمارك لمنع أي نفاذ عشوائي وغير مصرح به.",
          "اقتصار التدقيق على مؤشرات الفواتير والأرقام الكلية دون كشف الأسماء أو الحسابات الصغرى."
        ],
        riskNote: "بروتوكولات الحماية تغلق النوافذ البرمجية نهائياً ضد التدفق المالي العابر دون إذن رسمي.",
        acceptanceMessage: "تم تدقيق عزل الإيرادات: لا تسلل مالي، تم عزل وتأمين الدفاتر بنسبة 100%."
      },
      ku: {
        title: "تدقیق و عزلکردنی داهات و گومرگی سەروەری",
        shortExplanation: "سەلماندنی پاراستنی داتابەیسی داهات لە نێوان وەزارەتەکانی دارایی هەولێر و بەغدا.",
        talkingPoints: [
          "تۆماری دارایی فیدراڵی بە هیچ شێوازێک دەستکاری ناکرێت لەلایەن کایەکانی هەرێمەوە",
          "دۆخی داهاتی نەوتی و گومرگی هەرێم پارێزراوە لە هەر چوونەژوورەوەیەکی فیدراڵی",
          "تەنیا ئامار و نیشاندەرە گشتییەکان پشتڕاست دەکرێنەوە بۆ بودجە بەبێ ئاشکراکردنی ناوەکان"
        ],
        riskNote: "برۆتۆکۆلی پاراستنی داهات بە تەواوی جوڵەی گومانی و دزەکردن بلۆک دەکات.",
        acceptanceMessage: "تدقیقی داهات ئەنجامدرا: ئەنجامی دزەکردنی داتا سفرە."
      }
    },
    customs_flow: {
      id: "customs_flow",
      en: {
        title: "Decentralized Customs & HS-Code Pipeline",
        shortExplanation: "Demonstrate entry manifest creation and automated tariff verification across targets.",
        talkingPoints: [
          "HS-code values are unified globally but processed locally near the point of entry",
          "Cross-checks automated manifest rules to block unauthorized non-tariff cargo",
          "Decentralized customs clearance ensures robust trade speed"
        ],
        riskNote: "Only cleared cargo stats are dispatched to the joint database layer.",
        acceptanceMessage: "Customs execution verified: Anti-leak customs declarations compliant."
      },
      ar: {
        title: "دورة البيانات الجمركية والتعرفة اللامركزية",
        shortExplanation: "توضيح سيكولوجية إشهار البيانات التلقائي للسلع مع تفادي الغش التجاري والضريبي.",
        talkingPoints: [
          "معالجة الرموز المنسقة للجمارك (HS-Codes) محلياً لضمان السرعة والدقة الجمركية.",
          "مطابقة آلية لمنع تهريب البضائع غير المرخصة جمركياً أو المعفاة دون وجه حق.",
          "التخليص الجمركي الفوري عبر نقاط جمركية موزعة وآمنة تدعم التدفق التجاري السريع."
        ],
        riskNote: "يتم إرسال إحصاءات البضائع المصرح عنها فقط، والبيانات الفردية تبقى في خوادم المنفذ.",
        acceptanceMessage: "تم فحص دورة البيانات الجمركية: خالية من الفساد ومطابقة للمعايير الوطنية."
      },
      ku: {
        title: "ڕەوتی بەڵگەنامەی گومرگی و کۆدە جیهانییەکان",
        shortExplanation: "تاقیکردنەوەی دروستکردنی لێپرسینەوە و بەراوردکاری گومرگی لە سەرجەم مۆدیولەکاندا.",
        talkingPoints: [
          "پڕۆسەکردنی کۆدە جیهانییەکانی کاڵا (HS-Codes) لە شوێنی دەروازەکە بۆ دڵنیایی زیاتر",
          "هاوتاکردنی ڕێساکان بە شێوازی ئۆتۆماتیکی بۆ بلۆککردنی سەرپێچییەکانی گومرگی",
          "سیستەمی لامەرکەزی گومرگی کە خێرایی بازرگانی بە شێوەیەکی بەرچاو بەرز دەکاتەوە"
        ],
        riskNote: "تەنها داتای گومرگی ڕێگەپێدراو دەنێردرێت بۆ کایەی هاوبەشی بەراوردکاری لۆکاڵی.",
        acceptanceMessage: "پڕۆسەی گومرگ پشتڕاستکرایەوە: هیچ هەوڵێکی گەندەڵی جێبەجێ نەکراوە."
      }
    },
    border_flow: {
      id: "border_flow",
      en: {
        title: "Comprehensive Border Intelligence Patrol",
        shortExplanation: "Live monitoring of frontier checkpoints, transit corridors, and biometric checks.",
        talkingPoints: [
          "Real-time biometric validation logs process templates strictly in local HSM buffers",
          "E-gate checkpoints operate completely isolated and raise threat alarms on mismatches",
          "Integrates threat classifications and live alerts from borders without raw leaks"
        ],
        riskNote: "Under no circumstances are raw biometrics shared across jurisdictional systems.",
        acceptanceMessage: "Border system verified: 0% biometric leak rate, border security confirmed."
      },
      ar: {
        title: "منظومة المراقبة والاستخبارات الحدودية السريعة",
        shortExplanation: "عرض چاودێری البوابات الذكية وفحص الشاحنات بالأشعة ومقارنة البصمات في الميدان.",
        talkingPoints: [
          "التحقق اللحظي للبصمات والسمات الحيوية محلياً دون إرسال البيانات الأصلية.",
          "تشغيل البوابات الإلكترونية وإطلاق الإنذارات الأمنية عند رصد تفاوت البيانات.",
          "إرسال مؤشرات الخطورة الأمنية فقط للخوادم المشتركة لحماية سرية المخبرين."
        ],
        riskNote: "لا يتم تخزين أو مشاركة أي رسم حيوي (بصمة وجه أو قزحية) خارج الغرف الحصينة.",
        acceptanceMessage: "تم تدقيق أمن الحدود: صفر تسريب للبصمات والسمات، الحدود مؤمنة بالكامل."
      },
      ku: {
        title: "چاودێری و پاراستنی دەروازە سنورییەکان",
        shortExplanation: "بینینی جوڵەی بڕینی دەروازەکان و پشکنینەکان و ناسینەوەی تاکی بەکارهێنەر.",
        talkingPoints: [
          "خوێندنەوەی تایبەتمەندییە بایۆمەترییەکانی هاوڵاتی تەنها لەناو بافەری دەروازەکەدا",
          "کارکردنی دەروازەی ئەلیکترۆنی بۆ ڕێگریکردن لە هەر هەوڵێکی نایاسایی تێپەڕبوون",
          "یەکخستنی ئاڵۆزییە ئەمنییەکان لەگەڵ پاراستنی تەواوی نهێنی داتاکان"
        ],
        riskNote: "هیچ زانیارییەکی بایۆمەتری ئەسڵی نادرێت بە هیچ لایەنێکی دەرەکی یان ناوەندی.",
        acceptanceMessage: "سیستەمی سنور پشتڕاستکرایەوە: دەروازەکان بە تەواوی ئامادەن لە دەرەوەی دزەکردن."
      }
    },
    anti_corruption: {
      id: "anti_corruption",
      en: {
        title: "Automated Governance & Leakage Defense",
        shortExplanation: "Verify transparency engines that audit cross-border trade and valuation mismatches.",
        talkingPoints: [
          "Cross-references import cargo valuation parameters automatically to detect tax evasion",
          "Flags split-routing attempts where importers try to bypass unified border taxes",
          "Integrates tamper-proof audit trails for instant inter-governmental review"
        ],
        riskNote: "Integrity alerts protect raw private trade secrets and expose public volumes only.",
        acceptanceMessage: "Anti-corruption validated: Operational leak prevention is fully active."
      },
      ar: {
        title: "منظومة النزاهة والشفافية ومكافحة التهرب المالي",
        shortExplanation: "محرك التحقق التلقائي للأسعار والضرائب المطبقة لكشف أي محاولات للاختراق المالي.",
        talkingPoints: [
          "مقاطعة أسعار الشحن ونوع البضاعة تلقائياً لكشف تزييف الفواتير وتجنب الرسوم.",
          "رصد التوجيه الجمركي المشبوه الذي يسعى لتفادي الرسوم الاتحادية الموحدة.",
          "تأصيل سجلات غير قابلة للتعديل والمسح لتوفير الشفافية الكاملة للهيئات الرقابية."
        ],
        riskNote: "تتحرى الإنذارات الأمنية سلامة البيانات مع حماية السرية التامة لعقود الاستيراد الأصلية.",
        acceptanceMessage: "تم تقييم الشفافية والنزاهة: مكافحة التهرب فعالة ومؤمنة بنسبة 100%."
      },
      ku: {
        title: "ڕووبەڕووبوونەوەی گەندەڵی و جێبەجێکردنی شەفافیەت",
        shortExplanation: "بەدواداچوون بۆ ڕێگریکردن لە لادانی نرخەکان و تەهروبی گومرگی.",
        talkingPoints: [
          "بەراوردکاری نرخ و دیاریکردنی جۆری کاڵاکان بە شێوازێکی بێ لایەن",
          "دیاریکردن و هۆشداریدانی خێرا لە کاتی جوڵەی گومانی گومرگ بەبێ لادان",
          "دروستکردنی ڕاپۆرتی لێپرسینەوە پارێزراو بۆ لایەنەکان بە شێوازی فەرمی"
        ],
        riskNote: "سیستەمی هۆشداریدان تەنها داتای لادان نیشان دەدات لە دەرەوەی فرۆشتنی زانیاری.",
        acceptanceMessage: "ڕووبەڕووبوونەوەی گەندەڵی پشتڕاستکرایەوە: تاقیکردنەوەکان سەرکەوتووبوون."
      }
    },
    lang_switching: {
      id: "lang_switching",
      en: {
        title: "Integrated Trilingual Execution Engine",
        shortExplanation: "Demonstrates 100% complete UI translations across English, Arabic, and Kurdish layout models.",
        talkingPoints: [
          "Seamless localized experience engineered using pure zero-overload React state",
          "Maintains high-contrast typography and precise directional text layout across targets",
          "Trilingual labels mapped with pristine consistency in constitutional files"
        ],
        riskNote: "Ensures translation dictionaries do not share state with active data query pipelines.",
        acceptanceMessage: "Localization verified: Trilingual runtime fully operational across panels."
      },
      ar: {
        title: "محرك اللغات الثلاث المتكامل الرقابي",
        shortExplanation: "تأكيد الدعم الكامل للغات الثلاث في كامل عناصر لوحات التحكم لخدمة الكوادر الوطنية.",
        talkingPoints: [
          "تجربة ترجمة فورية مدمجة بالكامل دون تحميل خوادم البيانات أو إبطاء الأداء.",
          "الحفاظ على اتساق الواجهات ومحاذاة الشاشات من اليمين لليسار وبالعكس بسلاسة.",
          "تطابق كامل للمصطلحات القانونية والدستورية المقرة في القوانين السارية."
        ],
        riskNote: "فصل ملفات اللغات والترجمة كلياً عن محاور تبادل واستعلام البيانات الحساسة للحدود.",
        acceptanceMessage: "تم تدقيق اللغات: توافق كامل وتوطين للغات الثلاث بنسبة 100%."
      },
      ku: {
        title: "سیستەمی داینامیکی هەر سێ زمانی نیشتیمانی",
        shortExplanation: "نیشاندانی گۆڕینی زمانەکان بە شێوازی خێرا بەپێی ویستی بەکارهێنەر.",
        talkingPoints: [
          "گۆڕینی زمان بێ هیچ ڕاوەستانێک لە کارکردنی ڕووکاری سەرەکی",
          "ڕێکخستنی شێوازی دەق و نیشاندانی چاک لە ڕاست بۆ چەپ و بە پێچەوانەوە",
          "گونجانی بێ مەرجی مۆدیولە زمانەوانییەکان لەگەڵ زمانەکانی ئینگلیزی، عەرەبی، و کوردی"
        ],
        riskNote: "فایلەکانی زمان جیاکراونەتەوە لە هێڵە ئەمنییەکانی گواستنەوەی داتا.",
        acceptanceMessage: "زمانەکان سەرکەوتووبوون: مۆدیولەکان کاردەکەن لەگەڵ هەموو لایەنەکان."
      }
    }
  };

  public static getNarrative(id: string): ScenarioNarrative {
    return this.narratives[id] || this.narratives.joint_view;
  }

  public static getLocalizedNarrative(id: string, lang: 'en' | 'ar' | 'ku'): NarrativeDetail {
    const narrative = this.getNarrative(id);
    return narrative[lang] || narrative.en;
  }
}
