export const common = {
  overview: "تێڕوانینی گشتی",
  borderManager: "بەڕێوەبردنی دەروازە سنوورییەکان",
  activeGates: "دەروازە چالاکەکان",
  transitRecords: "کۆنووسەکانی گواستنەوە",
  cargoValuation: "بهای کاڵای هاوردەکراو",
  complianceRate: "ڕێژەی پابەندبوونی گومرگی",
  compoundRiskIndex: "نیشاندەری مەترسی گشتی",
  totalFines: "غەرامە گومرگییەکان",
  actions: "کردارەکان",
  status: "بارودۆخ",
  registeredGates: "دەروازە تۆمارکراوەکان",
  transitLog: "تۆماری گواستنەوەی کاڵا و گەشتیاران",
  inspections: "پشکنینی گومرگی و ئەمنی",
  riskAlerts: "ئاگادارکردنەوەکانی مەترسی",
  telemetryDevices: "ئامێرەکانی پەیوەندی و چاودێری",
  identityAuditChain: "تۆماری مۆری ئەلیکترۆنی (Audit Ledger)",
  registerTransit: "تۆمارکردنی گواستنەوەی نوێ",
  performInspection: "کارپێکردنی پشکنینی گومرگی نوێ",
  resolveAlert: "چارەسەرکردنی مەترسی",
  regulatoryPolicies: "یاساکان و ڕێنماییە گومرگییەکان",
  gateName: "ناوی دەروازە",
  gateType: "جۆری دەروازە",
  utilization: "ڕێژەی بەکارهێنان",
  riskScore: "ئاستی مەترسی",
  jurisdiction: "دەسەڵاتی دادوەری",
  authority: "فەرماندەیی بەرپرسیار",
  auditHash: "مۆری بلۆکچین",
  prevHash: "مۆری پێشوو",
  timestamp: "کاتی تۆمارکردن",

  borderOpsTitle: "چاودێری دەروازە سنوورییەکان و داهاتی گومرگی",
  borderOpsDesc: "سەنتەری هاوبەشی فیدراڵ-هەرێم بۆ تۆمارکردن، چاودێریکردن، خەمڵاندنی بەهای کاڵاکان و ڕێگری لە قاچاخچێتی و ڕاکردنی باج.",
  pulseActivity: "چالاککردنی بزووتنەوەی گواستنەوە",
  nationalPulse: "سیستەمی سیمولاتیۆنی چاودێری نیشتمانی",
  civPaxCenter: "ناوەندی پێشوازی مەدەنی و لۆجستی",
  intlInspector: "بەڕێوەبەرایەتی پشکنینی دەروازەی نێودەوڵەتی",
  normalInspection: "پشکنینی گومرگی ئاسایی ئەنجام درا بەبێ تێبینی دەکات.",
  qualityInspectionCommittee: "لیژنەی پشکنین و کۆنترۆڵی جۆری",
  antiSmugglingRoom: "ژووری کارپێکردنی ڕێگری لە قاچاخچێتی",
  economicProtectionCommittee: "لێژنەی باڵای پاراستنی ئابووری نیشتمانی",
  securityProtocol: "پرۆتۆکۆڵی ئاسایشی دەروازەی نیشتمانی کارایە:",
  levelJointCooperative: "ئاستی-٤-هاوبەش-هەرەوەزی",
  onlyShowingRecords: "تەنها ئەو تۆمارانە پیشان دەدرێن کە سەر بەم دەسەڵاتەن:",
  dbIsolationEnforced: "جیاکردنەوەی بنکەی زانیاری سنوورەکان جێبەجێ کراوە.",
  searchPlaceholder: "گەڕان بەپێی ناو یان ناسنامە...",
  fedSovereigntyRule: "بنەمای بەڕێوەبردنی گشتی دەروازەکان:",
  borderTetherText: "مۆری پشتڕاستکردنەوە نیشتمانییەکان بۆ دۆزینەوەی فرتوفێڵی دارایی و ڕاکردنی باج لەگەڵ وەزارەتەکانی فیدراڵ و هەرێم یارمەتیدەر دەبن بەپێی بڕگەی گشتی ١٤.",
  selectCheckpoint: "دەروازە دەستنیشان بکە",
  transitType: "جۆری گواستنەوە",

  cargoMachinery: "مەکینە و مۆلیدەی کارەبایی",
  cargoRaw: "کەرەستەی خاو و کانزایی",
  cargoFood: "خواردەمەنی و بەرهەمی پەلەوەر",
  cargoClothing: "جلوبەرگ و بەرهەمی قوماش",
  cargoWeightPlaceholder: "کێشی کەرەستە لە مانیفێست بەراورد کرا...",
};
