import { DigitalIdentity } from './IdentityTypes';

export const CORE_GOVERNMENT_IDENTITIES: DigitalIdentity[] = [
  // Federal Iraq Prime Minister & Executive Cabinets
  {
    id: 'EMP-FED-001',
    nationalId: 'IQ-110293-8472',
    fullName: 'Mustafa Al-Hashimi',
    email: 'mustafa.hashimi@pm.gov.iq',
    organization: 'FEDERAL_IRAQ',
    directorate: 'Diwan of the Prime Minister',
    department: 'Executive Council',
    unit: 'Supreme Governance Unit',
    position: 'Prime Minister',
    grade: 'Excellency',
    clearanceLevel: 'top-secret',
    biometricStatus: 'verified',
    role: 'Federal Prime Minister',
    status: 'active',
    deviceTrusted: true,
  },
  {
    id: 'EMP-FED-002',
    nationalId: 'IQ-158291-7541',
    fullName: 'Zainab Al-Khafaji',
    email: 'zainab.khafaji@cabinet.gov.iq',
    organization: 'FEDERAL_IRAQ',
    directorate: 'Cabinet Secretariat',
    department: 'Policy Integrity Dept',
    unit: 'Strategic Evaluation Unit',
    position: 'Cabinet Secretary',
    grade: 'Grade-1',
    clearanceLevel: 'top-secret',
    biometricStatus: 'verified',
    role: 'Federal Cabinet',
    status: 'active',
    deviceTrusted: true,
  },
  // Federal Border, Customs, Revenue, Trade, Audit, Inv
  {
    id: 'EMP-FED-003',
    nationalId: 'IQ-189032-1590',
    fullName: 'General Ahmed Al-Abadi',
    email: 'ahmed.abadi@border.gov.iq',
    organization: 'FEDERAL_IRAQ',
    directorate: 'Federal Border Guard Command',
    department: 'Border Security Division',
    unit: 'Strategic Crossings Unit',
    position: 'Border Guard Director General',
    grade: 'General',
    clearanceLevel: 'top-secret',
    biometricStatus: 'verified',
    role: 'Federal Border Director',
    status: 'active',
    deviceTrusted: true,
  },
  {
    id: 'EMP-FED-004',
    nationalId: 'IQ-234201-9081',
    fullName: 'Ali Abdul-Hussein',
    email: 'ali.customs@customs.gov.iq',
    organization: 'FEDERAL_IRAQ',
    directorate: 'General Commission for Customs',
    department: 'Tariff & Audit Directorate',
    unit: 'Automated Revenue Collection',
    position: 'Director General of Customs',
    grade: 'Senior Director',
    clearanceLevel: 'secret',
    biometricStatus: 'verified',
    role: 'Federal Customs Director',
    status: 'active',
    deviceTrusted: true,
  },
  {
    id: 'EMP-FED-005',
    nationalId: 'IQ-394012-7023',
    fullName: 'Dr. Hussain Al-Safi',
    email: 'hussain.tax@revenue.gov.iq',
    organization: 'FEDERAL_IRAQ',
    directorate: 'General Commission for Taxes',
    department: 'Corporate Auditing',
    unit: 'Sovereign Treasury Collections',
    position: 'Director of Federal Revenue',
    grade: 'Senior Director',
    clearanceLevel: 'secret',
    biometricStatus: 'verified',
    role: 'Federal Revenue Director',
    status: 'active',
    deviceTrusted: true,
  },
  {
    id: 'EMP-FED-006',
    nationalId: 'IQ-439201-5722',
    fullName: 'Mohammed Al-Jubouri',
    email: 'mohammed.trade@trade.gov.iq',
    organization: 'FEDERAL_IRAQ',
    directorate: 'Ministry of Trade',
    department: 'Foreign Trade Policy Board',
    unit: 'Import & Tariff Regulation',
    position: 'Director of Import Licensing',
    grade: 'Grade-2',
    clearanceLevel: 'secret',
    biometricStatus: 'verified',
    role: 'Federal Trade Director',
    status: 'active',
    deviceTrusted: true,
  },
  {
    id: 'EMP-FED-007',
    nationalId: 'IQ-548102-3928',
    fullName: 'Adnan Al-Sudani',
    email: 'adnan.auditor@audit.gov.iq',
    organization: 'FEDERAL_IRAQ',
    directorate: 'Federal Board of Supreme Audit',
    department: 'Petrochemical & Customs Audit',
    unit: 'Anomaly Detection Unit',
    position: 'Senior Sovereign Auditor',
    grade: 'Senior Expert',
    clearanceLevel: 'top-secret',
    biometricStatus: 'verified',
    role: 'Federal Auditor',
    status: 'active',
    deviceTrusted: true,
  },
  {
    id: 'EMP-FED-008',
    nationalId: 'IQ-647192-4820',
    fullName: 'Col. Tariq Al-Rubaie',
    email: 'tariq.investigator@intelligence.gov.iq',
    organization: 'FEDERAL_IRAQ',
    directorate: 'Federal Commission of Integrity',
    department: 'Border Leakage Task Force',
    unit: 'Financial Crimes Investigation',
    position: 'Chief Integrity Investigator',
    grade: 'Colonel',
    clearanceLevel: 'top-secret',
    biometricStatus: 'verified',
    role: 'Federal Investigator',
    status: 'active',
    deviceTrusted: true,
  },

  // Kurdistan Region Government (KRG) Cabinet & Executive
  {
    id: 'EMP-KRG-001',
    nationalId: 'KR-249102-1294',
    fullName: 'Masrour Barzani',
    email: 'masrour.barzani@krg.gov.krd',
    organization: 'KRG',
    directorate: 'Office of the Prime Minister',
    department: 'KRG High Executive Council',
    unit: 'Regional Sovereign Desk',
    position: 'Prime Minister',
    grade: 'Excellency',
    clearanceLevel: 'top-secret',
    biometricStatus: 'verified',
    role: 'KRG Prime Minister',
    status: 'active',
    deviceTrusted: true,
  },
  {
    id: 'EMP-KRG-002',
    nationalId: 'KR-285011-8411',
    fullName: 'Dr. Rebin Salih',
    email: 'rebin.salih@cabinet.gov.krd',
    organization: 'KRG',
    directorate: 'Regional Council of Ministers',
    department: 'Policy & Transparency Coordination',
    unit: 'Ministerial Secretariat',
    position: 'Cabinet Secretary',
    grade: 'S-Grade 1',
    clearanceLevel: 'top-secret',
    biometricStatus: 'verified',
    role: 'KRG Cabinet',
    status: 'active',
    deviceTrusted: true,
  },
  {
    id: 'EMP-KRG-003',
    nationalId: 'KR-310292-4911',
    fullName: 'General Sherwan Kurdish',
    email: 'sherwan.kurdish@border.gov.krd',
    organization: 'KRG',
    directorate: 'KRG Border Security Command',
    department: 'Northern Border Protection',
    unit: 'Ibrahim Khalil Border Unit',
    position: 'Joint Border Force Director',
    grade: 'General',
    clearanceLevel: 'top-secret',
    biometricStatus: 'verified',
    role: 'KRG Border Director',
    status: 'active',
    deviceTrusted: true,
  },
  {
    id: 'EMP-KRG-004',
    nationalId: 'KR-429102-5812',
    fullName: 'Hiwa Rasool',
    email: 'hiwa.customs@customs.gov.krd',
    organization: 'KRG',
    directorate: 'General Customs Directorate of KRG',
    department: 'Regional Audit & Control',
    unit: 'Tariff Assessment Board',
    position: 'Director of KRG Customs Control',
    grade: 'Director',
    clearanceLevel: 'secret',
    biometricStatus: 'verified',
    role: 'KRG Customs Director',
    status: 'active',
    deviceTrusted: true,
  },
  {
    id: 'EMP-KRG-005',
    nationalId: 'KR-582012-3911',
    fullName: 'Media Sulaiman',
    email: 'media.revenue@revenue.gov.krd',
    organization: 'KRG',
    directorate: 'General Tax and Revenue Directory',
    department: 'Non-Tax Revenue Division',
    unit: 'Customs & Border Revenue',
    position: 'Revenue Assessment Officer',
    grade: 'Expert-2',
    clearanceLevel: 'secret',
    biometricStatus: 'verified',
    role: 'KRG Revenue Director',
    status: 'active',
    deviceTrusted: true,
  },
  {
    id: 'EMP-KRG-006',
    nationalId: 'KR-629102-4822',
    fullName: 'Soran Akreyi',
    email: 'soran.trade@trade.gov.krd',
    organization: 'KRG',
    directorate: 'Ministry of Trade & Industry',
    department: 'Import Licensing Division',
    unit: 'Regional Customs Oversight',
    position: 'Chief Trade Licensing Officer',
    grade: 'Director-3',
    clearanceLevel: 'secret',
    biometricStatus: 'verified',
    role: 'KRG Trade Director',
    status: 'active',
    deviceTrusted: true,
  },
  {
    id: 'EMP-KRG-007',
    nationalId: 'KR-720193-4712',
    fullName: 'Shavgar Sulaiman',
    email: 'shavgar.auditor@audit.gov.krd',
    organization: 'KRG',
    directorate: 'Supreme Audit Board of Kurdistan',
    department: 'Transparency Enforcement',
    unit: 'Compliance Oversight Unit',
    position: 'Senior Regional Auditor',
    grade: 'Senior Advisor',
    clearanceLevel: 'top-secret',
    biometricStatus: 'verified',
    role: 'KRG Auditor',
    status: 'active',
    deviceTrusted: true,
  },
  {
    id: 'EMP-KRG-008',
    nationalId: 'KR-839102-1249',
    fullName: 'Aram Barzani',
    email: 'aram.integrity@integrity.gov.krd',
    organization: 'KRG',
    directorate: 'Commission of Public Integrity KRG',
    department: 'Financial Leakage Audits',
    unit: 'Northern Crossings Investigation',
    position: 'Senior Integrity Investigator',
    grade: 'Lead Expert',
    clearanceLevel: 'top-secret',
    biometricStatus: 'verified',
    role: 'KRG Investigator',
    status: 'active',
    deviceTrusted: true,
  },

  // Joint Operations & Oversight Committees
  {
    id: 'EMP-JNT-001',
    nationalId: 'JT-920192-4812',
    fullName: 'Dr. Tariq Al-Kurdi',
    email: 'tariq.kurdi@joint.gov.iq',
    organization: 'JOINT_OPERATIONS',
    directorate: 'Joint Executive Council',
    department: 'Federal-Regional Coordination',
    unit: 'Inter-governmental Secretariat',
    position: 'Joint Executive Coordinator',
    grade: 'EX-Director',
    clearanceLevel: 'top-secret',
    biometricStatus: 'verified',
    role: 'Joint Coordinator',
    status: 'active',
    deviceTrusted: true,
  },
  {
    id: 'EMP-JNT-002',
    nationalId: 'JT-102941-8592',
    fullName: 'Faris Al-Gailani',
    email: 'faris.board@joint.gov.iq',
    organization: 'JOINT_OPERATIONS',
    directorate: 'Joint Revenue Administration Board',
    department: 'Revenue Reconciliation Committee',
    unit: 'Tariff Equalization Staff',
    position: 'Executive Director of Joint Revenue',
    grade: 'Expert-1',
    clearanceLevel: 'secret',
    biometricStatus: 'verified',
    role: 'Joint Revenue Board',
    status: 'active',
    deviceTrusted: true,
  },
  {
    id: 'EMP-JNT-003',
    nationalId: 'JT-284910-1842',
    fullName: 'Brigadier General Kamal Erbil',
    email: 'kamal.border@joint.gov.iq',
    organization: 'JOINT_OPERATIONS',
    directorate: 'Joint Border Control Secretariat',
    department: 'Operational Integrity Division',
    unit: 'Ibrahim Khalil Joint Guard Desk',
    position: 'Co-Director of Joint Borders',
    grade: 'Brigadier General',
    clearanceLevel: 'top-secret',
    biometricStatus: 'verified',
    role: 'Joint Border Committee',
    status: 'active',
    deviceTrusted: true,
  },
  {
    id: 'EMP-JNT-004',
    nationalId: 'JT-384920-5812',
    fullName: 'Nadia Sulaimany',
    email: 'nadia.trade@joint.gov.iq',
    organization: 'JOINT_OPERATIONS',
    directorate: 'Joint Trade Harmonization Council',
    department: 'Customs Interoperability Division',
    unit: 'Import Clearance Desk',
    position: 'Trade Facilitation Director',
    grade: 'Grade-2',
    clearanceLevel: 'secret',
    biometricStatus: 'verified',
    role: 'Joint Trade Committee',
    status: 'active',
    deviceTrusted: true,
  },
  {
    id: 'EMP-JNT-005',
    nationalId: 'JT-492042-1920',
    fullName: 'Yousif Al-Barzanji',
    email: 'yousif.integrity@joint.gov.iq',
    organization: 'JOINT_OPERATIONS',
    directorate: 'Joint Sovereign Integrity Committee',
    department: 'Financial Transparency Oversight',
    unit: 'Anti-smuggling Audit Force',
    position: 'General Integrity Secretary',
    grade: 'Lead Commissioner',
    clearanceLevel: 'top-secret',
    biometricStatus: 'verified',
    role: 'Joint Integrity Committee',
    status: 'active',
    deviceTrusted: true,
  }
];

export class IdentityRegistry {
  private static identities: DigitalIdentity[] = [...CORE_GOVERNMENT_IDENTITIES];

  public static getAll(): DigitalIdentity[] {
    return this.identities;
  }

  public static getById(id: string): DigitalIdentity | undefined {
    return this.identities.find(emp => emp.id === id);
  }

  public static getByEmail(email: string): DigitalIdentity | undefined {
    return this.identities.find(emp => emp.email.toLowerCase() === email.toLowerCase());
  }

  public static getByNationalId(nationalId: string): DigitalIdentity | undefined {
    return this.identities.find(emp => emp.nationalId === nationalId);
  }

  public static registerIdentity(identity: DigitalIdentity): void {
    if (this.identities.some(emp => emp.id === identity.id)) {
      throw new Error(`Employee ID ${identity.id} is already registered.`);
    }
    this.identities.push(identity);
  }

  public static updateIdentity(id: string, updates: Partial<DigitalIdentity>): void {
    const idx = this.identities.findIndex(emp => emp.id === id);
    if (idx === -1) throw new Error(`Employee ID ${id} not found.`);
    this.identities[idx] = { ...this.identities[idx], ...updates };
  }
}
