export const common = {
  overview: "نظرة عامة",
  borderManager: "إدارة المنافذ الحدودية",
  activeGates: "المنافذ النشطة",
  transitRecords: "سجلات العبور",
  cargoValuation: "تقييم البضائع",
  complianceRate: "نسبة الامتثال الجمركي",
  compoundRiskIndex: "مؤشر المخاطر المركب",
  totalFines: "الغرامات المفروضة",
  actions: "الإجراءات",
  status: "الحالة",
  registeredGates: "المنافذ المسجلة",
  transitLog: "سجل العبور للبضائع والمسافرين",
  inspections: "الفحوصات الجمركية والأمنية",
  riskAlerts: "تنبيهات المخاطر المخالفة",
  telemetryDevices: "أجهزة القياس والاستشعار",
  identityAuditChain: "سجل التدقيق الإلكتروني الموثق",
  registerTransit: "تسجيل حركة عبور جديدة",
  performInspection: "إجراء فحص جمركي جديد",
  resolveAlert: "معالجة التنبيه",
  regulatoryPolicies: "الاتفاقيات واللوائح التنظيمية للحدود",
  gateName: "اسم المنفذ",
  gateType: "نوع المنفذ",
  utilization: "نسبة الاستخدام",
  riskScore: "تقييم المخاطر",
  jurisdiction: "الاختصاص القضائي",
  authority: "السلطة المسؤولة",
  auditHash: "مؤشر التجزئة",
  prevHash: "التجزئة السابقة",
  timestamp: "وقت التسجيل",

  borderOpsTitle: "نموذج السيطرة على المنافذ والجمارك السيادية",
  borderOpsDesc: "المركز الفيدرالي الإقليمي المشترك لإدارة المنافذ لتنسيق عمليات العبور، احتساب التعرفة الجمركية، والحد من التهرب الجمركي.",
  pulseActivity: "توليد حركة تجارية",
  nationalPulse: "نظام محاكاة المراقبة الوطنية",
  civPaxCenter: "مركز الاستقبال المدني واللوجستي",
  intlInspector: "مديرية تفتيش المنافذ الدولية",
  normalInspection: "تم الفحص الجمركي الروتيني دون ملاحظات.",
  qualityInspectionCommittee: "لجنة الفحص والسيطرة النوعية",
  antiSmugglingRoom: "غرفة عمليات مكافحة التهريب",
  economicProtectionCommittee: "اللجنة العليا لحماية الاقتصاد الوطني",
  securityProtocol: "بروتوكول أمن المنافذ السيادي نشط:",
  levelJointCooperative: "مستوى-4-تعاوني-مشترك",
  onlyShowingRecords: "يتم عرض السجلات المرتبطة بالولاية القضائية فقط:",
  dbIsolationEnforced: "تم فرض عزل قاعدة البيانات عبر الحدود.",
  searchPlaceholder: "البحث بالاسم أو المعرف...",
  fedSovereigntyRule: "قاعدة السيادة الفيدرالية:",
  borderTetherText: "تلتزم جميع المنافذ المشتركة بنسخ داتا البضائع والبيان الجمركي إلكترونياً وبشكل فوري لكل من بغداد وأربيل بموجب المادة 14.",
  selectCheckpoint: "اختر منفذ العبور",
  transitType: "نوع العبور",

  cargoMachinery: "معدات ومولدات كهربائية",
  cargoRaw: "المواد الخام والمعادن",
  cargoFood: "المواد الغذائية ومنتجات الدواجن",
  cargoClothing: "الملابس والمنسوجات",
  cargoWeightPlaceholder: "تم التحقق من وزن الحمولة في البيان الجمركي...",
};
